In [1]:
import numpy as np

Задание 1. Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента

In [6]:
a = [[1,6], [2,7], [3,8], [4,9], [5,10]]
a = np.array(a)

In [7]:
a

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [14]:
mean_a = a.mean(axis=0)
print(f'Средние значения по признакам - ', mean_a[0], ' и ', mean_a[1])

Средние значения по признакам -  3.0  и  8.0


Задание 2. Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [16]:
a_centered = a - mean_a
a_centered

array([[-2., -2.],
       [-1., -1.],
       [ 0.,  0.],
       [ 1.,  1.],
       [ 2.,  2.]])

Задание 3. Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [25]:
a_centered_transp = np.transpose(a_centered)
a_centered_sp = a_centered_transp[0] @ a_centered_transp[1]
a_centered_sp/4

2.5

Задание 4. В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [22]:
m = np.transpose(a)
m_cov = np.cov(m)
m_cov

array([[2.5, 2.5],
       [2.5, 2.5]])